apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-partition-0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
      partition: "0"
  template:
    metadata:
      labels:
        app: client
        partition: "0"
    spec:
      containers:
      - name: client
        image: iso8583-client:latest
        env:
        - name: CLIENT_PARTITION
          value: "0"
        - name: TOTAL_PARTITIONS
          value: "2"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-partition-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
      partition: "1"
  template:
    metadata:
      labels:
        app: client
        partition: "1"
    spec:
      containers:
      - name: client
        image: iso8583-client:latest
        env:
        - name: CLIENT_PARTITION
          value: "1"
        - name: TOTAL_PARTITIONS
          value: "2"