---
apiVersion: v1
kind: Service
metadata:
  name: iso8583-grpc-service
  labels:
    app: iso8583-server
spec:
  selector:
    app: iso8583-server
  ports:
    - name: grpc
      protocol: TCP
      port: 9090
      targetPort: 9090
  type: ClusterIP
  clusterIP: None