apiVersion: v1
kind: Service
metadata:
  name: simulator-service
  namespace: default
spec:
  selector:
    app: simulator
  ports:
  - name: iso 
    port: 8084
    targetPort: 8084
    protocol: TCP
  type: ClusterIP
